### PR TITLE
replaced 'MASTER_RCAT' by 'PRIMARY_RCAT' to be compatible to 4.3.0

### PR DESCRIPTION
**Pull request by joergsteinkamp**
Dear iRODS-developers,
I've realized, there is no 4-3-stable branch here yet. Nevertheless, since we rely on kerberos, I was able to compile this plugin with this patch for 4-3-stable.
Greetings
Jörg

### CODE REVIEW

**Comment by korydraughn** [comment]
There are no plans to support the Kerberos plugin in iRODS 4.3.0 at this time.

Even though this code compiles, it will most likely result in incorrect behavior due to the following commit:
- https://github.com/irods/irods/commit/f65dfef5a6129a6f7e2456e0df56ec8415321b8c

The plan is to off-load all authentication to a new PAM plugin implemented on top of the new auth plugin framework. Doing this would enable several other authentication schemes, including Kerberos. This has the nice benefit of simplifying authentication in iRODS as well.

We are working with the community to implement a PAM plugin that achieves this. You can find that code here:
- https://github.com/stefan-wolfsheimer/irods/tree/interactive_pam

This work is driven by the auth working group. You can read all about this here:
- https://github.com/irods-contrib/irods_working_group_authentication

**Comment by cmeesters** [comment]
Hi,

Sounds great. However, it seems the entered password is present in its scrambled display when using this method. 

This on a multi-user system with a known descrambling script is a recipe for disaster. Can you confirm? Or comment on this?

Cheers
Christian

**Comment by joergsteinkamp** [comment]
Hi Kory,

so if i get it right, I have only option to switch to PAM authentication, if I want to update to v4.3. Currently the PAM-Password/Username is sent to the server via SSL, the user is authenticated and a 'random' string is returned to the client, which is saved in the scrambled password file and used for a certain period (TTL; time to live) to authenticate against the irods-server. I have some questions, which I did not find in the code:

1.) Is this random-password automatically updated or does the user have to reidentify against PAM after TTL?
2.) If it is the case of automatic password updates, what about a real end of life for the password? For example, a user with a locked account could otherwise still log into iRODS.
3.) Can I configure this TTL somewhere?

Nevertheless, even if it is not the system-password saved in the scrambled password-file and in the database (table r_user_password?), I need to check if that is allowed at all by our security policy.

Thanks & kind regards
Jörg

**Comment by korydraughn** [comment]
The scrambled text does not contain your actual password. It contains a _limited_ password generated by the server. The limited password also depends on the UID.

The TTL is managed by the server administrator and not by the client. When the TTL expires, the user will be required to re-authenticate with the iRODS server. Passwords are not automatically updated.

Keep in mind that iRODS has its own TTL values around PAM.

**Comment by joergsteinkamp** [comment]
Hi Kory,

I guess, since it's not in the docs, the correct place to define it is as mentioned by Terrel here: https://github.com/irods/irods/issues/4904
If that's the case, just close my pull request and I will start implenting PAM.

Jörg

**Comment by korydraughn** [comment]
Keep in mind that Kerberos is not supported by the 4.3.0 PAM plugin yet.

If you need Kerberos, your best option is to continue using 4.2.11 until the work from the new PAM implementation is released.

**Comment by korydraughn** [comment]
@alanking Please close this PR.

**Comment by joergsteinkamp** [comment]
Hi Kory,

I set up a test server (however still 4.2.6) with PAM and it did work with our kerberos system. Nevertheless, that would be another topic, I close the PR.

Jörg

**Pull request closed without merging**
